import csv
import importlib.util
import json
import os
import re
import subprocess
import sys
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

_REPO = Path(__file__).resolve().parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

Path("data").mkdir(parents=True, exist_ok=True)

_COOKIE_JAR = _REPO / "data" / ".xhs_curl_cookie_jar.txt"


def _write_curl_cookie_jar(cookies: dict[str, str]) -> Path | None:
    """Netscape 格式供 curl -b 使用（避免 Cookie 值含 ; 时 -b 字符串断裂）。"""
    if not cookies:
        return None
    lines = ["# Netscape HTTP Cookie File", "# Generated by xhs_crab.py"]
    for name, value in cookies.items():
        lines.append(
            f".xiaohongshu.com\tTRUE\t/\tFALSE\t0\t{name}\t{value}"
        )
    _COOKIE_JAR.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return _COOKIE_JAR


def _curl_cookie_argv() -> list[str]:
    """与 Core API 共用 data/xhs_cookie.txt（除非 TENCLIP_XHS_NO_COOKIE=1）。"""
    if os.environ.get("TENCLIP_XHS_NO_COOKIE", "").strip().lower() in ("1", "true", "yes"):
        return []
    try:
        path = _REPO / "subprojects" / "core_api" / "xhs_preview.py"
        spec = importlib.util.spec_from_file_location("xhs_preview", path)
        if not spec or not spec.loader:
            return []
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        cookies = mod._merged_cookie_dict()
    except Exception:
        return []
    if not cookies:
        return []
    jar = _write_curl_cookie_jar(cookies)
    return ["-b", str(jar)] if jar else []


data = defaultdict(list)
with open("data/xhs_notes.csv", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        tax = row["taxnonomy1_name"].strip()
        nid = row["note_id"].strip()
        data[tax].append(nid)


def fetch_note(tax, nid):
    url = f"https://www.xiaohongshu.com/explore/{nid}"

    try:
        curl_cmd = [
            "curl",
            "-s",
            "-L",
            "--compressed",
            "--max-time",
            "20",
            "-A",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "-H",
            "Accept-Language: zh-CN,zh;q=0.9",
            "-H",
            f"Referer: {url}",
            *_curl_cookie_argv(),
            url,
        ]
        result = subprocess.run(
            curl_cmd,
            capture_output=True,
            text=True,
            timeout=25,
        )

        html = result.stdout

        def get_meta(prop):
            esc = re.escape(prop)
            m = re.search(
                rf'<meta[^>]+(?:property|name)=["\']{esc}["\'][^>]+content=["\']([^"\']*)["\']',
                html,
                re.I,
            )
            if not m:
                m = re.search(
                    rf'<meta[^>]+content=["\']([^"\']*)["\'][^>]+(?:property|name)=["\']{esc}["\']',
                    html,
                    re.I,
                )
            return m.group(1) if m else ""

        title = get_meta("og:title")
        image = get_meta("og:image")
        likes = get_meta("og:xhs:note_like")
        duration = get_meta("og:videotime")
        note_type = get_meta("og:xhs:note_type")

        bad_titles = ("用万能旅行拍照姿势美美出片", "万能旅行拍照姿势")
        if title and any(b in title for b in bad_titles):
            title = ""

        out = {
            "tax": tax,
            "nid": nid,
            "url": url,
            "title": title,
            "image": image,
            "likes": likes,
            "duration": duration,
            "note_type": note_type,
            "ok": bool(title),
        }
        if not out["ok"]:
            out["reason"] = "empty og:title (likely wall / need cookie or residential IP)"
            il = (image or "").lower()
            if "picasso-static" in il or "fe-platform" in il:
                out["reason"] += "; og:image is fe placeholder, not note cover"
            if _curl_cookie_argv():
                out["reason"] += "; cookie jar was sent — try refreshing data/xhs_cookie.txt"
            else:
                out["reason"] += "; no cookie loaded (check data/xhs_cookie.txt)"
        return out

    except Exception as e:
        return {"tax": tax, "nid": nid, "url": url, "error": str(e), "ok": False}


tasks = [(tax, nid) for tax, nids in data.items() for nid in nids]
results = []
with ThreadPoolExecutor(max_workers=10) as executor:
    futures = {executor.submit(fetch_note, tax, nid): (tax, nid) for tax, nid in tasks}
    done = 0
    for future in as_completed(futures):
        r = future.result()
        results.append(r)
        done += 1
        if r["ok"]:
            t = r["title"] or ""
            print(f"{done}/{len(tasks)} OK {r['tax']} {r['nid']} {t[:50]}")
        else:
            msg = (r.get("error") or r.get("reason") or "unknown")[:120]
            print(f"{done}/{len(tasks)} ERROR {r['tax']} {r['nid']} {msg}")

out_path = Path("data/xhs_crab_meta.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

okcount = sum(1 for r in results if r["ok"])
print(f"OK: {okcount}/{len(tasks)} ({okcount / len(tasks):.2%})  -> {out_path}")
